version: '3.6'

services:
  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - 5432
    volumes:
      - ./migrations/20211024021847_create_shorturl_service.up.sql:/docker-entrypoint-initdb.d/20211024021847_create_shorturl_service.up.sql



  server:
    image: shorturlservice
    build:
      context: ./
      dockerfile: shorturlservice.dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
    links:
      - database